# Generated by Django 4.0.5 on 2022-07-17 11:21

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'Female')], max_length=50)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('cv', models.FileField(blank=True, null=True, upload_to='user_cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('level', models.CharField(choices=[('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('ENTRY_LEVEL', 'Entry level')], default='ENTRY_LEVEL', max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('city_alert', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.city')),
                ('skills', models.ManyToManyField(blank=True, to='skills.skill')),
            ],
            options={
                'verbose_name': 'Employee',
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(max_length=50)),
                ('company_size', models.CharField(choices=[('LESS_50', 'Less than 50'), ('50_200', 'From 50 to 200'), ('200_500', 'From 200 to 500'), ('MORE_500', 'More than 500')], default='LESS_50', max_length=50)),
                ('started_at', models.DateField()),
                ('website', models.URLField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.city')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': '',
                'managed': True,
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
