# Generated by Django 4.0.5 on 2022-07-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True, 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee'},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('LESS_50', 'Less than 50'), ('50_200', 'From 50 to 200'), ('200_500', 'From 200 to 500'), ('MORE_500', 'More than 500')], default='LESS_50', max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table='',
        ),
    ]
