# Generated by Django 4.0.5 on 2022-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('LESS_50', 'Less than 50'), ('50_200', 'From 50 to 200'), ('200_500', 'From 200 to 500'), ('MORE_500', 'More than 500')], default='LESS_50', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
