# Generated by Django 4.0.5 on 2022-07-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_company_company_size_alter_employee_dob_and_more'),
        ('profiles', '0002_alter_employee_dob_alter_employee_job_title'),
    ]

    operations = [
    ]
