# Generated by Django 4.0.5 on 2022-07-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('profiles', '0002_alter_company_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='skills_employee_id', to='skills.skill'),
        ),
    ]
