# Generated by Django 4.0.5 on 2022-07-22 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.city'),
        ),
        migrations.AlterField(
            model_name='company',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
