# Generated by Django 4.0.5 on 2022-07-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_company_about_alter_company_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
