# Generated by Django 4.0.5 on 2022-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_employee_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('LESS_50', 'Less than 50'), ('50_200', 'From 50 to 200'), ('200_500', 'From 200 to 500'), ('MORE_500', 'More than 500')], default='LESS_50', max_length=50, null=True),
        ),
    ]
