# Generated by Django 4.0.5 on 2022-07-03 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('ENTRY-LEVEL', 'Entry-level')], max_length=50)),
                ('Description', models.TextField()),
                ('job_type', models.CharField(choices=[('FULLTIME', 'Full-Time'), ('PARTTIME', 'Part-Time'), ('INTERN', 'Internship')], max_length=50)),
                ('work_type', models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite'), ('HYBRID', 'Hybrid')], max_length=50)),
                ('salary', models.IntegerField()),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Company')),
                ('skills', models.ManyToManyField(to='skills.skill')),
            ],
        ),
    ]
