# Generated by Django 4.0.5 on 2022-07-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedemployees',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
