# Generated by Django 4.0.5 on 2022-07-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
    ]
