# Generated by Django 4.0.5 on 2022-07-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedemployees',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
