# Generated by Django 4.0.5 on 2022-07-24 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salaries', '0002_alter_salary_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_company_id', to=settings.AUTH_USER_MODEL, verbose_name='Company'),
        ),
    ]
