# Generated by Django 4.0.5 on 2022-07-04 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('employment_status', models.CharField(choices=[('FULLTIME', 'Full-Time'), ('PARTTIME', 'Part-Time'), ('INTERN', 'Internship')], max_length=50)),
                ('rating', models.IntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_company_id', to=settings.AUTH_USER_MODEL, verbose_name='Company')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_employee_id', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
        ),
    ]
