# Generated by Django 4.0.5 on 2022-07-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_state_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='employment_status',
            field=models.CharField(choices=[('FULLTIME', 'Full-Time'), ('PARTTIME', 'Part-Time'), ('INTERN', 'Internship')], default='FULLTIME', max_length=50),
        ),
    ]
