# Generated by Django 4.0.5 on 2022-07-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('questions', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_company_id', to=settings.AUTH_USER_MODEL, verbose_name='Company ID')),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_employee_id', to=settings.AUTH_USER_MODEL, verbose_name='Developer ID')),
            ],
        ),
    ]
